name: Publish PR
description: Publish a PR if it has a specific label
inputs:
  java-distribution:
    description: JDK vendor (zulu, temurin, etc.)
    default: zulu
  java-version:
    description: Java version to setup (25)
    default: "25"
  memory-limit:
    description: Memory limit for sbt (2048 MB)
    default: "2048"
  cache-key:
    description: Cache key
    default: target
  command:
    description: Test command to run
    default: test
runs:
  using: "composite"
  steps:
       - name: Push ephemeral environment
         shell: bash
         run: |
              echo "Checking out code ${{ github.event.pull_request.number }}"
              echo " Unlabeling ${{ github.event.label.name }}"
              VERSION="pr-${{ github.event.pull_request.number }}"
              echo "Pushing ephemeral environment for version $VERSION"
       - name: Tag PR for ArgoCD
         uses: actions-ecosystem/action-add-labels@v1
         with:
            github_token: ${{ github.token }}
            labels: "argocd/review"