name: Compile
description: Compiles the project
inputs:
  checkout:
    description: Whether to checkout the code (true/false)
    default: "true"
  checkout-submodules:
    description: Whether to checkout submodules (true/false)
    default: "true"
  scala-version:
    description: Scala version to use for tests (2, 2.13, 3 ... etc...)
    default: ""
  java-distribution:
    description: JDK vendor (zulu, temurin, etc.)
    default: zulu
  java-version:
    description: Java version to setup (25)
    default: "25"
  memory-limit:
    description: Memory limit for sbt (2048 MB)
    default: "2048"
  cache-key:
    description: Cache key
    default: target
  command:
    description: Compile command to run
    default: compile; Test / compile
  
runs:
  using: "composite"
  steps:
    - name: Checkout code
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v5
      with:
        submodules: ${{ inputs.checkout-submodules }}
    - name: Set up Scala
      uses: /WorldOfScala/actions/setup-sbt@master
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Cache lookup
      id: compilation-cache
      if: ${{ !contains(github.event.pull_request.body, 'ci:skip-cache') }}
      uses: /WorldOfScala/actions/restore-compilation-cache@master
      with:
        key: ${{ inputs.cache-key }}-${{ inputs.scala-version }}

    - name: Compile (main & tests)
      shell: bash
      run: |
       if [ "${{ inputs.scala-version }}" != "" ]; then
         sbt -mem ${{ inputs.memory-limit }} '++ ${{ inputs.scala-version }}; ${{ inputs.command }}'
       else
         sbt -mem ${{ inputs.memory-limit }} '${{ inputs.command }}'
       fi

    - name: Upload tests compilation cache
      uses: actions/cache/save@v4
      with:
        path: |
          target/scala*/*test*
          modules/**/target/scala*/*test*
        key: ${{ inputs.cache-key }}-${{ inputs.scala-version }}-tests-${{ hashFiles('build.sbt') }}-${{ hashFiles('modules/**/src/test/scala/**') }}

    - name: Upload main compilation cache
      uses: actions/cache/save@v4
      with:
        path: |
          target/
          modules/**/target/
          project/target
        key: ${{ inputs.cache-key }}-${{ inputs.scala-version }}-main-${{ hashFiles('build.sbt') }}-${{ hashFiles('modules/**/src/main/scala/**') }}
