name: Compile
description: Compiles the project
inputs:
  cache-key:
    description: Cache key
    default: target
runs:
  using: 'composite'
  steps:

    - name: Cache lookup
      id: compilation-cache
      if: ${{ !contains(github.event.pull_request.body, 'ci:skip-cache') }}
      uses: /WorldOfScala/actions/restore-compilation-cache@master
      with:
        key: ${{ inputs.cache-key }}

    - name: Compile (main & tests)
      shell: bash
      run: sbt 'compile; Test / compile'

    - name: Upload tests compilation cache
      uses: actions/cache/save@v4
      with:
        path: |
          target/scala*/*test*
          modules/**/target/scala*/*test*
        key: ${{ inputs.cache-key }}-tests-${{ hashFiles('build.sbt') }}-${{ hashFiles('modules/**/src/test/scala/**') }}

    - name: Upload main compilation cache
      uses: actions/cache/save@v4
      with:
        path: |
          target/
          modules/**/target/
          project/target
        key: ${{ inputs.cache-key }}-main-${{ hashFiles('build.sbt') }}-${{ hashFiles('modules/**/src/main/scala/**') }}

