name: Restore compilation cache
description: Restore compilation cache
inputs:
  key:
    description: Cache key
    default: target
  scala-version:
    description: Scala version to use for tests ("++ 2.13;" "++ 3;", etc...)
    default: ""

outputs:
  cache-hit:
    description: Cache hit
    value: ${{ steps.impl_main.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Restore main compilation cache (${{ inputs.key }})
      id: impl_main
      uses: actions/cache/restore@v4
      with:
        path: |
          target/
          modules/**/target/
          project/target
        key: ${{ inputs.key }}-${{ inputs.scala-version }}-main-${{ hashFiles('build.sbt') }}-${{ hashFiles('modules/**/src/main/scala/**') }}
        restore-keys: |
          ${{ inputs.key }}-${{ inputs.scala-version }}-main-${{ hashFiles('build.sbt') }}
          ${{ inputs.key }}-${{ inputs.scala-version }}-main
          ${{ inputs.key }}-${{ inputs.scala-version }}
    - name: Restore tests compilation cache (${{ inputs.key }})
      id: impl_tests
      uses: actions/cache/restore@v4
      with:
        path: |
          target/scala*/*test*
          modules/**/target/scala*/*test*
        key: ${{ inputs.key }}-${{ inputs.scala-version }}-tests-${{ hashFiles('build.sbt') }}-${{ hashFiles('modules/**/src/test/scala/**') }}
        restore-keys: |
          ${{ inputs.key }}-${{ inputs.scala-version }}-tests-${{ hashFiles('build.sbt') }}
          ${{ inputs.key }}-${{ inputs.scala-version }}-tests
          ${{ inputs.key }}-${{ inputs.scala-version }}
