name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Restore compilation cache
        uses: /WorldOfScala/actions/compile@master
      - name: Run test (main & tests)
        shell: bash
        run: sbt 'test'
